### ISSUE TITLE
Error: Channel closed by server: 405 (RESOURCE-LOCKED)

### ISSUE THREAD

**Issue by richzw** [amqp-node/amqplib#139]
I meet one exception

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Channel closed by server: 405 (RESOURCE-LOCKED) with message "RESOURCE_LO
CKED - cannot obtain exclusive access to locked queue 'UI' in vhost '/'"
    at ConfirmChannel.C.accept (c:\share\node\node_modules\amqplib\lib\channel.j
s:399:24)
    at Connection.mainAccept [as accept] (c:\share\node\node_modules\amqplib\lib
\connection.js:62:33)
    at Socket.go (c:\share\node\node_modules\amqplib\lib\connection.js:465:48)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

How to caught this exception?

Should I use 

``` javascript
process.on('uncaughtException', function (err) {
  console.error(err.stack);
  console.log("Node NOT Exiting...");
});
```

**Comment by squaremo** [comment]
Adding an `'error'` handler to the channel will let you handle the error yourself, so it doesn't become an uncaughtException.
