### ISSUE TITLE
channel.ack should not return until the message is done sending and we have a success or error

### ISSUE THREAD

**Issue by maxedmands** [amqp-node/amqplib#190]
Hi @squaremo, thanks for this incredibly useful library. It's central to our infra here at @goodeggs.

I'm trying to write a test for a failure case we've encountered in our code, in which we try and `channel.ack()` after the connection has already been closed. (Kinda like #143.) I am having a lot of trouble actually getting this test to fail, however.

At a high level, it looks something like this:

``` javascript
it('does not allow a message to ack after disconnecting', function() {
  channel.close();
  expect(function() { channel.ack(message) }).to.throw(/connection closing/i)
});
```

This test fails, and right afterwards, I get a stack trace that looks like this:

```
Unhandled rejection IllegalOperationError: Connection closing
  at Connection.<anonymous> (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/amqplib/lib/connection.js:354:11)
  at ConfirmChannel.C.sendImmediately (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/amqplib/lib/channel.js:63:26)
  at ConfirmChannel.C.ack (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/amqplib/lib/channel_model.js:224:8)
  at /Users/maxedmands/Projects/goodeggs-domain-events/src/index.coffee:494:18
  at /Users/maxedmands/Projects/goodeggs-domain-events/src/index.coffee:515:16
  at tryCatcher (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/promise.js:503:31)
  at Promise._settlePromiseAt (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/promise.js:577:18)
  at Promise._settlePromises (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/promise.js:693:14)
  at Async._drainQueue (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/async.js:133:10)
  at Async.drainQueues (/Users/maxedmands/Projects/goodeggs-domain-events/node_modules/bluebird/js/main/async.js:15:14)
  at process._tickCallback (node.js:448:13)

```

I would really like my test to look more like this:

``` javascript
it('does not allow a message to ack after disconnecting', function() {
  channel.close();
  expect(channel.ack(message)).to.eventually.be.rejectedWith(/connection closing/i);
  // (using chai-as-promised: https://github.com/domenic/chai-as-promised/)
});
```

**Comment by squaremo** [comment]
> It's central to our infra here at @goodeggs.

Cool! I'm happy it's being put to use :)

Just to confirm my reading of the situation: it looks from the stack trace that the amqplib.Channel.ack is called inside a promise -- which means the when it throws an exception, the exception is caught and funneled through the reject handler. `Channel#disconnect` isn't in amqplib, so is `channel` a wrapper of some kind?

**Comment by demands** [comment]
Ah yes, my apologies @squaremo: we are using a wrapper with a `disconnect` method that does various housekeeping activities before calling `channel.close()`. I've corrected my code in the initial issue to reflect this.

**Comment by cressie176** [comment]
Here's an example using `channel.get` and `channel.consume`. The consume variant is complicated because if an error is thrown from within the consume callback it can get intercepted by amqplib.

```javascript
const assert = require('assert');
const amqp = require('amqplib');

let connection;

before(async () => {
  connection = await amqp.connect();
})

after(async () => {
  if (connection) await connection.close();
})

it('issue 190 using channel.get', async () => {
  const channel = await connection.createConfirmChannel();
  await channel.assertQueue('test');
  await channel.purgeQueue();

  channel.sendToQueue('test', Buffer.from('foo'));
  await channel.waitForConfirms();

  const message = await channel.get('test', { noAck: false });

  channel.close();
  assert.throws(() => channel.ack(message), { message: 'Channel closing' })
})

it('issue 190 using channel.consume', (done) => {
  (async () => {
    const channel = await connection.createConfirmChannel();
    await channel.assertQueue('test');
    await channel.purgeQueue();

    channel.sendToQueue('test', Buffer.from('foo'));
    await channel.waitForConfirms();

    const consumerTag = `X-${Math.random}`;
    await channel.consume('test', async (message) => {
      try {
        await channel.cancel('abc');
        channel.close();
        assert.throws(() => channel.ack(message), { message: 'Channel closing' })
        done();
      } catch (err) {
        done(err)
      }
    }, { noAck: false, consumerTag })
  })();
})
```
