### ISSUE TITLE
Cannot send message with relatively large header

### ISSUE THREAD

**Issue by achinaou** [amqp-node/amqplib#363]
To be able to consume a message with the relatively large header I need to set `frameMax=0x0000` to disable the limit but if I want to `sendToQueue` this message with the relatively large header I get this error on the client side:

```
Error: Connection closed: 541 (INTERNAL-ERROR) with message "INTERNAL_ERROR"
    at Object.accept (/.../node_modules/amqplib/lib/connection.js:90:15)
    at Connection.mainAccept [as accept] (/.../node_modules/amqplib/lib/connection.js:63:33)
    at Socket.go (/.../node_modules/amqplib/lib/connection.js:476:48)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:502:10)
    at emitReadable (_stream_readable.js:496:7)
    at addChunk (_stream_readable.js:263:7)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)
```

**Comment by cressie176** [comment]
He max header size was increased in 2019. Hopefully the [new value](https://github.com/amqp-node/amqplib/pull/545/files) is sufficient.

**Comment by achinaou** [comment]
Maybe this could be configurable?

**Comment by cressie176** [comment]
Maybe. The change was made in the generate-defs file, which actually generates the contents of lib/defs.js at build time from [amqp-rabbitmq-0.9.1.json](https://raw.githubusercontent.com/rabbitmq/rabbitmq-codegen/rabbitmq_v3_2_1/amqp-rabbitmq-0.9.1.json). For this reason it might be somewhat harder to get configuration into the right places at the right time. I'm sure it would be possible though.
