### ISSUE TITLE
Feature Request: Nicer errors when priority is higher than X-Max-Priority

### ISSUE THREAD

**Issue by will3942** [amqp-node/amqplib#380]
When trying to send a message to a queue with a priority > than the max priority set for the queue the only error you get is:

```
TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1178:11)
    at Buffer.writeUInt8 (buffer.js:1226:5)
    at encodeBasicProperties (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/amqplib/lib/defs.js:2886:12)
    at module.exports.encodeProperties (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/amqplib/lib/defs.js:3544:12)
    at Connection.C.sendMessage (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/amqplib/lib/connection.js:542:16)
    at Channel.C.sendMessage (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/amqplib/lib/channel.js:85:26)
    at Channel.C.publish (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/amqplib/lib/channel_model.js:158:15)
    at Channel.C.sendToQueue (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/amqplib/lib/channel_model.js:162:15)
    at /Users/will3942/work/Spotlight Data/node-dispatcher/helpers/tasks/convertTasksToPublishPromises.js:21:15
    at tryCatcher (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/will3942/work/Spotlight Data/node-dispatcher/node_modules/bluebird/js/release/promise.js:432:57)
```

This was rather confusing to find that it was the message priority being greater than the queue's max priority.

A nicer error message would be good!

**Comment by cressie176** [comment]
Looking at the stack trace, the problem is that you tried to use a value bigger than the maximum value for an unsigned byte (i.e. 255). You can reproduce directly using

```js
const buf = Buffer.allocUnsafe(1);
buf.writeUInt8(256, 0);
```

With node v8 the message is

```
> const buf = Buffer.allocUnsafe(1);
TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1185:11)
    at Buffer.writeUInt8 (buffer.js:1233:5)
```

But with latter version you get the min and max range

```
internal/buffer.js:737
    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);
    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 255. Received 256
    at new NodeError (internal/errors.js:322:7)
    at writeU_Int8 (internal/buffer.js:737:11)
    at Buffer.writeUInt8 (internal/buffer.js:747:10)
    at Object.<anonymous> (/Users/steve/Development/cressie176/amqplib-640/index.js:2:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_OUT_OF_RANGE'
}
```
The code which calls this function is actually [generated](https://github.com/amqp-node/amqplib/blob/main/bin/generate-defs.js) from this [json document](https://raw.githubusercontent.com/rabbitmq/rabbitmq-codegen/rabbitmq_v3_2_1/amqp-rabbitmq-0.9.1.json). It might still be possible to provide a better error message, however I think could be misleading since, while the physical maximum of an unsigned byte is 255, there may be other rules for specific attributes meaning the valid maximum is lower.
