### ISSUE TITLE
Unhandled Rejection in promise error in channel.js after qpidj start throttling messages

### ISSUE THREAD

**Issue by mvtm-dn** [amqp-node/amqplib#482]
I've got such type of error when qpidj starts to throttling messages. 
Stacktrace:
```
Unhandled Rejection at: Promise [object Promise] reason Error: Expected BasicQosOk; got <ChannelFlow channel:3>
Error: Expected BasicQosOk; got <ChannelFlow channel:3>
at reply (/.../node_modules/amqplib/lib/channel.js:106:17)
at Channel.C.accept (/.../node_modules/amqplib/lib/channel.js:433:12)
at Connection.mainAccept [as accept] (/.../node_modules/amqplib/lib/connection.js:64:33)
at Socket.go (/.../node_modules/amqplib/lib/connection.js:477:48)
at emitNone (events.js:106:13)
at Socket.emit (events.js:208:7)
at emitReadable_ (_stream_readable.js:513:10)
at emitReadable (_stream_readable.js:507:7)
at addChunk (_stream_readable.js:274:7)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:607:20)
```

**Comment by cressie176** [comment]
If I understand correctly you were using something like [QPID Broker J](https://qpid.apache.org/components/broker-j/index.html) with amqplib. It looks like QPID Broker J supports Channel Flow control however according to [this comment](https://github.com/amqp-node/amqplib/blob/243aef8b6da766a3b9908bc50b2be4859eef43a6/lib/channel.js#L432), RabbitMQ and amqplib do not. Hence after sending the Basic.Qos instruction, amplib was expecting the Basic.QoS-Ok confirmation, and does not handle the Basic.Flow instruction.
