### ISSUE TITLE
Different failure handling behaviour on channel method call if mandatory input parameter is not specified

### ISSUE THREAD

**Issue by PaulAnnekov** [amqp-node/amqplib#575]
Here is a code:

```
const amqplib = require('amqplib');

async function main() {
    const connection = await amqplib.connect('connection_uri');
    connection.on('error', (...args) => console.log('connection error', args));
    connection.on('close', (...args) => console.log('connection close', args));

    const channel = await connection.createChannel();
    channel.on('error', () => {
        console.log('channel error', arguments);
    });

    try {
        console.log('before trigger reply');
        channel.assertQueue('asd');
        console.log('before cancel');
        await channel.cancel();
        console.log('after cancel');
    } catch (err) {
        console.log('cancel error', err);
    }
}

console.log('before main');
main();
console.log('after main');
```

This code emits the following output:

```
before main
after main
before trigger reply
before cancel
connection error [ Error: Missing value for mandatory field 'consumerTag'
      at encodeBasicCancel (.../node_modules/amqplib/lib/defs.js:1984:29)
      at module.exports.encodeMethod (.../node_modules/amqplib/lib/defs.js:3471:12)
      at Connection.C.sendMethod (.../node_modules/amqplib/lib/connection.js:530:15)
      at Channel.C.sendImmediately (.../node_modules/amqplib/lib/channel.js:70:26)
      at Channel.C.accept (.../node_modules/amqplib/lib/channel.js:449:12)
      at Connection.mainAccept [as accept] (.../node_modules/amqplib/lib/connection.js:64:33)
      at Socket.go (.../node_modules/amqplib/lib/connection.js:478:48)
      at Socket.emit (events.js:198:13)
      at emitReadable_ (_stream_readable.js:554:12)
      at process._tickCallback (internal/process/next_tick.js:63:19) ]
connection close [ Error: Missing value for mandatory field 'consumerTag'
      at encodeBasicCancel (.../node_modules/amqplib/lib/defs.js:1984:29)
      at module.exports.encodeMethod (.../node_modules/amqplib/lib/defs.js:3471:12)
      at Connection.C.sendMethod (.../node_modules/amqplib/lib/connection.js:530:15)
      at Channel.C.sendImmediately (.../node_modules/amqplib/lib/channel.js:70:26)
      at Channel.C.accept (.../node_modules/amqplib/lib/channel.js:449:12)
      at Connection.mainAccept [as accept] (.../node_modules/amqplib/lib/connection.js:64:33)
      at Socket.go (.../node_modules/amqplib/lib/connection.js:478:48)
      at Socket.emit (events.js:198:13)
      at emitReadable_ (_stream_readable.js:554:12)
      at process._tickCallback (internal/process/next_tick.js:63:19) ]
cancel error { Error: Channel ended, no reply will be forthcoming
    at rej (.../node_modules/amqplib/lib/channel.js:201:7)
    at Channel.C._rejectPending (.../node_modules/amqplib/lib/channel.js:203:28)
    at Channel.C.toClosed (.../node_modules/amqplib/lib/channel.js:171:8)
    at Connection.C._closeChannels (.../node_modules/amqplib/lib/connection.js:394:18)
    at Connection.C.toClosed (.../node_modules/amqplib/lib/connection.js:401:8)
    at Connection.C.onSocketError (.../node_modules/amqplib/lib/connection.js:355:10)
    at Connection.emit (events.js:198:13)
    at Socket.go (.../node_modules/amqplib/lib/connection.js:481:12)
    at Socket.emit (events.js:198:13)
    at emitReadable_ (_stream_readable.js:554:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  cause:
   Error: Channel ended, no reply will be forthcoming
       at rej (.../node_modules/amqplib/lib/channel.js:201:7)
       at Channel.C._rejectPending (.../node_modules/amqplib/lib/channel.js:203:28)
       at Channel.C.toClosed (.../node_modules/amqplib/lib/channel.js:171:8)
       at Connection.C._closeChannels (.../node_modules/amqplib/lib/connection.js:394:18)
       at Connection.C.toClosed (.../node_modules/amqplib/lib/connection.js:401:8)
       at Connection.C.onSocketError (.../node_modules/amqplib/lib/connection.js:355:10)
       at Connection.emit (events.js:198:13)
       at Socket.go (.../node_modules/amqplib/lib/connection.js:481:12)
       at Socket.emit (events.js:198:13)
       at emitReadable_ (_stream_readable.js:554:12)
       at process._tickCallback (internal/process/next_tick.js:63:19),
  isOperational: true }
```

Connection error with subsequent connection close.

But if you will remove these 2 lines:
```
console.log('before trigger reply');
channel.assertQueue('asd');
```

the output and behavior will be different:

```
before main
after main
before cancel
cancel error Error: Missing value for mandatory field 'consumerTag'
    at encodeBasicCancel (.../node_modules/amqplib/lib/defs.js:1984:29)
    at module.exports.encodeMethod (.../node_modules/amqplib/lib/defs.js:3471:12)
    at Connection.C.sendMethod (.../node_modules/amqplib/lib/connection.js:530:15)
    at Channel.C.sendImmediately (.../node_modules/amqplib/lib/channel.js:70:26)
    at Channel.C.sendOrEnqueue (.../node_modules/amqplib/lib/channel.js:81:10)
    at Channel.C._rpc (.../node_modules/amqplib/lib/channel.js:142:8)
    at .../node_modules/amqplib/lib/channel_model.js:182:10
    at tryCatcher (.../node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (.../node_modules/bluebird/js/release/promise.js:209:30)
    at Channel.C.cancel (.../node_modules/amqplib/lib/channel_model.js:181:18)
    at main (.../poc_amqp_bug.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

as you can see, it's a method error, channel and connection are not invalidated and it looks reasonable compared to first output.

For me it looks like a bug triggering connection `error` when we detect wrong input parameter before send.

**Comment by cressie176** [comment]
Closing as this is an old issue. However the problem is very likely to be that `assertQueue` is missing an await. Consequently the channel is in use at the point `cancel` is called without the mandatory consumerTag. This breaks the channel which interferes with the creation of the queue resulting in a second, separate error.

**Comment by SeraPayFinTech** [comment]
This issue still persists, even with an async promise

**Comment by cressie176** [comment]
@SeraPayFinTech

The original issue was most likely because the code didn't await the `channel.assert` operation, so that when the channel was broken by the invalid`channel.cancel` operation, things got funky. Assuming I am correct, this isn't a bug with amqp, it's a bug with the way amqp was being used.

If you share a minimal example that reproduces the problem you are experiencing, I am happy to take a look.
