### ISSUE TITLE
Amqp protocol localhost connect request is unsuccessful even when rabbitmq is up

### ISSUE THREAD

**Issue by 12sam12** [amqp-node/amqplib#694]
In my findings:  (File: node_modules/amqplib/lib/connect.js)
```javascript
if (protocol === 'amqp:') {
    sock = require('net').connect(sockopts, onConnect);
  }
```
control never enters the onConnect callback function. This is from source code of amqplib. "net" is nodejs's internal socket connectivity library.

Also the following is my sockopts object:
```javascript
{
host: 'localhost', 
servername: 'localhost', 
port: 5672
}
```
Im using node v 16 (But it happens in 18.0.0 as well). I also find the net package is fine in v 16 as well (https://nodejs.org/docs/latest-v16.x/api/net.html#socketconnect)
![image](https://user-images.githubusercontent.com/13358855/177259689-63b1dc14-4571-4e6d-832f-8d528108a7e0.png)
![image](https://user-images.githubusercontent.com/13358855/177277421-717d0f0e-357a-4d3b-92ff-b8ca86973cd3.png)
![image](https://user-images.githubusercontent.com/13358855/177259749-f12fcb8f-29d7-4a3e-8e85-22e66fc9ba10.png)

Any ideas?

**Comment by cressie176** [comment]
Most likely amqplib is unable to connect because of a configuration or network issue. Try setting a socket timeout so that amqplib doesn't hang indefinitely

```js
const amqplib = require('amqplib/callback_api');

const socketOptions = {
  timeout: 10000
}
amqplib.connect('amqp://localhost', socketOptions, (err, connection) => {
  if (err) throw err;
  console.log('Connected');
  connection.close((err) => {
    if (err) throw err;        
  })
})
```

**Comment by 12sam12** [comment]
Now its returning: But I get error:

Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Connection.C.sendBytes (/node_modules/amqplib/lib/connection.js:527:15)
    at Connection.C.sendProtocolHeader (/node_modules/amqplib/lib/connection.js:118:8)
    at Connection.C.open (/node_modules/amqplib/lib/connection.js:287:8)
    at Socket.onConnect (/node_modules/amqplib/lib/connect.js:149:7)
    at Object.onceWrapper (node:events:509:28)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1147:10)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by cressie176** [comment]
Hi @12sam12,

I think you're confusing the RabbitMQ HTTP RESTful API and the amqp protocol. This library only uses amqp. With amqp you do not connect to queues by specifying the queue name in the connection string, you connect to the broker only then use the [channel api](https://amqp-node.github.io/amqplib/channel_api.html). 

Often client applications have only one connection per Virtual Host, but you may decide to have one connection for consuming messages, and user a second one for publishing.
