### ISSUE TITLE
TypeError: connection.createChannel is not a function

### ISSUE THREAD

**Issue by kizouker** [amqp-node/amqplib#711]
TypeError: connection.createChannel is not a function

    at /Users/raberg/Library/Mobile Documents/com~apple~CloudDocs/Code/microservices/init.js:14:38
    at Object.<anonymous> (/Users/raberg/Library/Mobile Documents/com~apple~CloudDocs/Code/microservices/init.js:33:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {stack: 'TypeError: connection.createChannel is not a …    at internal/main/run_main_module.js:17:47', message: 'connection.createChannel is not a function'}

**Comment by cressie176** [comment]
Hi @kizouker,
Please reopen this issue completing the information requested in the issue template.
Thank you
