### ISSUE TITLE
I'm encountering an "Unexpected close" error

### ISSUE THREAD

**Issue by kundan8239** [amqp-node/amqplib#753]
Environment: ubuntu 18
Node Version: v18.2.0

service:rabbit Unexpected close +3m
Error: Unexpected close
    at succeed (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:280:13)
    at onOpenOk (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:262:5)
    at /Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:165:32
    at /Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:159:12
    at Socket.recv (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:507:12)
    at Object.onceWrapper (node:events:641:28)
    at Socket.emit (node:events:527:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
  service:rabbit Trying to reconnect to amqp://localhost +1ms
  service:rabbit RabbitMQ disconnected +0ms
Error: RabbitMQ disconnected
    at Rabbit.<anonymous> (/Users/kundank/one/workspace/sauron/src/services/rabbit.js:25:38)
    at Rabbit.emit (node:events:527:28)
    at Rabbit.emitDisconnected (/Users/kundank/one/workspace/sauron/node_modules/rabbit-queue/js/rabbit.js:62:14)
    at ConfirmChannel.<anonymous> (/Users/kundank/one/workspace/sauron/node_modules/rabbit-queue/js/rabbit.js:74:49)
    at ConfirmChannel.emit (node:events:539:35)
    at C.toClosed (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/channel.js:174:8)
    at C._closeChannels (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:402:18)
    at C.toClosed (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:409:8)
    at C.onSocketError (/Users/kundank/one/workspace/sauron/node_modules/amqplib/lib/connection.js:363:10)
    at Socket.emit (node:events:539:35)

**Comment by cressie176** [comment]
https://github.com/amqp-node/amqplib/issues/151#issuecomment-332443577

**Comment by cressie176** [comment]
Anything more we can help you with @kundan8239?
